Git和GitHub促进了开源软件的发展是因为消除了核心开发者和贡献者的隔阂——你若能看到代码，你就能改进代码。开放的电子书亦是如此，下面的贡献者让本书变得更好。

以贡献时间为序，感谢：

1. `Zhang Hailong <https://github.com/zhhailon>`_ 报告文字错误。问题： `#2 <https://github.com/gotgit/gotgithub/issues/2>`_ 。
2. `Riku <https://github.com/riku>`_ 纠正文字错误。提交： `455d0db`_ , `f244e3d`_ 。
3. `windwiny <https://github.com/windwiny>`_  纠正文字错误。提交： `1ed1a51`_

.. _455d0db: https://github.com/gotgit/gotgithub/commit/455d0db
.. _f244e3d: https://github.com/gotgit/gotgithub/commit/f244e3d
.. _1ed1a51: https://github.com/gotgit/gotgithub/commit/1ed1a51
